# Generated by Django 4.1 on 2022-09-20 19:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bungalow', 'bungalow'), ('Duplex', 'duplex'), ('Mansion', 'mansion'), ('Lekki', 'Lekki')], max_length=255),
        ),
    ]
